name: Publish Python 🐍 distribution 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
      - name: Install poetry
        run: python -m pip install poetry
      - name: Publish package
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish --build
